name: Deploy terraform files.
on:
  push:
    branches:
      - main

jobs:
  deploy_tf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run deploy script
        run: ./scripts/deploy.sh

